---
- hosts: local
  become: yes
  become_method: sudo
  remote_user: ubuntu

  tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
         update_cache: yes

  - name: install JDK 11
    apt:
      name: openjdk-11-jdk
      state: present

  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: download & unarchive
    unarchive:
            src: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.47/bin/apache-tomcat-8.5.47.tar.gz  
            dest: /opt/tomcat
            remote_src: yes
            extra_opts: [--strip-components=1]

  - name: Change ownership
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  - name: Copy Tomcat service from local to remote
    copy:
       src: /ansible/tomcat.service
       dest: /etc/systemd/system/tomcat.service
       mode: 0755

  - name: overwrite file if it exists context.xml from local to remote
    copy:
       src: /ansible/tomcat-users.xml
       dest: /opt/tomcat/conf/tomcat-users.xml
       follow: yes

  - name: overwrite file if it exists context.xml from local to remote
    copy:
       src: /ansible/context.xml
       dest: /opt/tomcat/webapps/manager/META-INF/context.xml
       follow: yes

  - name: overwrite file if it exists context.xml from local to remote
    copy:
       src: /ansible/context.xml
       dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml
       follow: yes

  - name: Start and enable Tomcat service
    service:
      daemon_reload: yes
      name: tomcat
      state: started
      enabled: yes
    when: ansible_service_mgr == "systemd" 
  
